---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96"
  module_defaults:
    group/aws:
      region: "us-east-2"
  tasks: 
    - name: Create temporary ec2 instance for staging
      ec2:
        key_name: auburncc
        group:
          - Module5-ig-dev-sg
          - Module5-ig-postgres-tag
        instance_type: t3.nano
        image: "{{ ami_id }}"
        wait: yes
        instance_tags:
          Name: M5dev
        assign_public_ip: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: M5dev
